# X-windows (or OpenWindows) link option files
xv:
	clm -sl xv -nr -nt -nw circuits -o circuits

xvs:
	clm -sl xvs -nr -nt -nw circuits -o circuits

x:
	clm -sl x -nr -nt -nw circuits -o circuits

xs:
	clm -sl xs -nr -nt -nw circuits -o circuits

# OpenWindows link option files only
olit:
	clm -sl olit -nr -nt -nw circuits -o circuits

olits:
	clm -sl olits -nr -nt -nw circuits -o circuits

# Remove all replaceable files
cleanup:
	$(RM) circuits \
	$(RM) *.abc \
	$(RM) *.o
	