/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/grads/charity1/CVS/charity/ParseLex/lex.yy.c,v 1.1.1.1 2000/02/25 22:40:55 danaha Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 139
#define YY_END_OF_BUFFER 140
static yyconst short int yy_accept[348] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  140,   46,   36,    1,
       45,   33,    2,    3,    4,    5,   22,   23,    8,   46,
       27,   38,   11,   25,   13,   32,   34,   35,    9,   46,
       10,   24,   35,   14,   19,   15,   12,   36,   35,   35,
      129,  127,  129,  129,  138,  131,  137,  130,  137,  139,
       87,   84,   77,   86,   78,   87,   85,   83,   81,   82,
       81,   82,   87,  100,   98,   88,   89,  100,   99,   95,
      100,  100,  100,  100,  100,  100,  100,  117,  115,  101,

      102,  117,  110,  111,  117,  116,  112,  105,  114,  114,
      114,  114,  114,  125,  123,  118,  121,  119,  125,  122,
      124,   52,   50,   47,   48,   52,   51,   58,   56,   53,
       54,   58,   57,   64,   62,   59,   60,   64,   63,   70,
       68,   65,   66,   70,   69,   76,   74,   71,   74,   75,
       72,   75,   36,    2,    2,   44,    6,   37,   21,   26,
       38,   20,   35,   39,   43,   41,   40,   42,   35,   35,
       16,    7,   18,   17,   36,    0,    0,   35,   35,   30,
      126,  128,  132,  136,  134,  133,  135,   84,   78,   78,
       79,    0,    0,   82,    0,   98,   89,   89,   90,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,  115,
      102,  102,  103,  113,  112,    0,    0,  114,  114,  114,
      114,  114,  123,  119,  119,  120,   50,   48,   48,   49,
       51,   56,   54,   54,   55,   57,   62,   60,   60,   61,
       63,   68,   66,   66,   67,   69,   74,   72,   72,   73,
       35,   29,    0,   30,   35,   35,    0,    0,   80,   93,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      114,  114,  114,  109,   28,    0,   35,   35,   81,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   94,    0,
      106,  114,    0,    0,   31,   35,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,   35,    0,    0,
        0,    0,    0,    0,    0,    0,  104,    0,    0,   35,
        0,    0,    0,    0,    0,   91,    0,    0,    0,  108,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   97,    0,   96,  107,   92,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,    8,   11,
       12,   13,   14,   15,   16,   17,    5,   18,   18,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,    5,
       23,   24,   25,   26,   27,   27,   28,   27,   29,   27,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   31,
       32,   33,   30,   34,   30,   30,   30,   35,   30,   30,
       36,   37,   38,    5,   39,    5,   40,   41,   42,   43,

       44,   45,   30,   46,   47,   30,   30,   48,   49,   50,
       51,   52,   53,   54,   55,   56,   57,   30,   30,   58,
       59,   30,   60,   61,   62,   63,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[64] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,    3,
        1,    1,    1,    1,    1,    1,    3,    3,    3,    2,
        2,    2,    2,    2,    2,    1,    1,    1,    2,    3,
        3,    3,    3,    3,    3,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    1,
        1,    1,    1
    } ;

static yyconst short int yy_base[372] =
    {   0,
        0,   62,   62,   65,   68,   80,    0,    0,  116,  170,
      224,  279,  335,    0,   85,   95,  126,  136,  148,  180,
      202,  227,  397,  441,  206,  249,  645,  646,   75,  646,
      646,  646,  641,  646,   71,  646,  646,  646,  646,   89,
      626,  142,  646,  646,  618,  646,  646,    0,  646,  214,
      646,  646,  102,  580,  102,  646,  646,  132,  583,   48,
      646,  646,  626,  626,  646,  646,  646,  646,  243,  646,
      646,  119,  646,  646,  634,  623,  646,  646,  646,  646,
      578,  111,  590,  646,  122,  646,  630,  619,  646,  646,
      140,  591,  118,  576,  585,   87,  574,  646,  176,  646,

      624,  613,  646,  646,  224,  646,  243,  192,    0,  574,
      567,  579,  578,  646,  210,  646,  646,  618,  607,  646,
      646,  646,  214,  646,  616,  605,  599,  646,  235,  646,
      613,  602,  182,  646,  264,  646,  611,  600,  255,  646,
      285,  646,  609,  598,    0,  646,  289,  646,  293,  646,
      607,  596,  296,  605,  646,  646,  646,  287,  646,  646,
      290,  646,    0,  646,  646,  646,  646,  646,  551,  561,
      646,  646,  646,  646,  400,  548,  559,  556,  562,    0,
      646,  646,  646,  646,  646,  646,  646,  309,  598,  646,
      646,  553,  559,  646,  542,  310,  594,  646,  646,  548,

      543,  538,  545,  542,  544,  538,  549,  534,  530,  313,
      583,  646,  646,  307,  310,  407,  544,    0,  535,  534,
      533,  525,  314,  577,  646,  646,  319,  576,  646,  646,
      560,  401,  574,  646,  646,  252,  408,  573,  646,  646,
      400,  419,  572,  646,  646,    0,  425,  571,  646,  646,
      533,    0,  525,  646,  515,  527,  513,  525,  646,  646,
      523,  526,  510,  522,  513,  514,  507,  503,  515,  507,
      516,  504,  551,    0,    0,  498,  426,  435,  646,  434,
      428,  421,  432,  419,  418,  433,  430,  429,  646,  410,
        0,  462,  408,  429,  430,  417,  416,  419,  399,  410,

      428,  413,  405,  393,  392,  390,  381,  387,  374,  362,
      361,  356,  298,  276,  251,  251,  646,  259,  248,  233,
      215,  214,  204,  190,  205,  646,  179,  143,  152,  646,
      134,  122,  113,  130,   97,   56,   55,   49,   59,   39,
       36,  646,   39,  646,  646,  646,  646,  486,  489,  492,
      495,  498,  501,  504,  507,  510,  513,  516,  519,  521,
      524,  527,  530,  532,  535,  538,  541,  544,  547,   64,
      550
    } ;

static yyconst short int yy_def[372] =
    {   0,
      347,    1,  348,  348,  349,  349,  350,  350,  351,  351,
      352,  352,  347,   13,  353,  353,  354,  354,  355,  355,
      356,  356,  357,  357,  358,  358,  347,  347,  347,  347,
      347,  347,  359,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  360,  347,  347,
      347,  347,  360,  347,  347,  347,  347,  347,  360,  360,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  361,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  362,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,

      363,  347,  347,  347,  347,  347,  347,  347,  364,  364,
      364,  364,  364,  347,  347,  347,  347,  365,  347,  347,
      347,  347,  347,  347,  366,  347,  347,  347,  347,  347,
      367,  347,  347,  347,  347,  347,  368,  347,  347,  347,
      347,  347,  369,  347,  370,  347,  347,  347,  347,  347,
      371,  347,  347,  359,  347,  347,  347,  347,  347,  347,
      347,  347,  360,  347,  347,  347,  347,  347,  360,  360,
      347,  347,  347,  347,  347,  347,  347,  360,  360,  360,
      347,  347,  347,  347,  347,  347,  347,  347,  361,  347,
      347,  347,  347,  347,  347,  347,  362,  347,  347,  347,

      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      363,  347,  347,  347,  347,  347,  347,  364,  364,  364,
      364,  364,  347,  365,  347,  347,  347,  366,  347,  347,
      347,  347,  367,  347,  347,  347,  347,  368,  347,  347,
      347,  347,  369,  347,  347,  370,  347,  371,  347,  347,
      360,  360,  347,  347,  360,  360,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      364,  364,  364,  364,  360,  347,  360,  360,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      364,  364,  347,  347,  347,  360,  347,  347,  347,  347,

      347,  347,  347,  347,  347,  347,  347,  360,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  360,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,    0,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347
    } ;

static yyconst short int yy_nxt[710] =
    {   0,
       28,   29,   30,   29,   28,   31,   32,   28,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   42,   42,
       43,   44,   45,   28,   46,   47,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   49,   50,   51,   52,   48,
       48,   48,   53,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   54,
       55,   56,   57,   58,   62,   58,  246,   62,   65,   65,
       66,  346,   63,   68,   64,   63,  153,   64,  153,  345,
       65,   65,   66,  156,  344,   68,  115,  116,  115,  343,
      117,  179,  180,  118,  342,  119,  115,  116,  115,  120,

      117,  121,  341,  118,   69,  119,  158,  158,  158,  120,
      260,  121,  159,  172,   59,   60,   69,   72,   73,   72,
      188,   74,  188,  196,   75,  196,   76,  123,  124,  123,
      207,  157,   77,  175,  125,  175,  126,  123,  124,  123,
       78,  169,  208,  127,  125,  170,  126,   79,   80,  129,
      130,  129,  340,  127,  193,  194,  131,  203,  132,  161,
      161,  161,  173,  174,  339,  133,  133,  260,   81,   82,
       83,   72,   73,   72,  204,   74,  260,  210,   75,  210,
       76,  129,  130,  129,  176,  177,   77,  200,  131,  338,
      132,  201,  337,  216,   78,  216,  336,  133,  133,  236,

      236,   79,   80,  135,  136,  135,  146,  147,  148,  149,
      137,  223,  138,  223,  151,  227,  152,  227,  335,  139,
      139,  139,   81,   82,   83,   85,   86,   85,  135,  136,
      135,  217,   87,  334,   88,  137,  232,  138,  232,  333,
       89,  214,  214,  214,  139,  139,  139,  332,   90,  146,
      147,  148,  149,  331,  164,  165,  166,  151,  194,  152,
      215,  215,  215,   91,  167,  237,   92,  237,   93,  236,
      236,  168,  241,  241,  241,   94,  180,   95,   96,   97,
       85,   86,   85,  183,  184,  185,  242,   87,  242,   88,
      247,  330,  247,  186,  247,   89,  247,  153,  329,  153,

      187,  328,  327,   90,  158,  158,  158,  161,  161,  161,
      188,  196,  188,  196,  210,  223,  210,  223,   91,  326,
      227,   92,  227,   93,  214,  214,  214,  215,  215,  215,
       94,  325,   95,   96,   97,   98,   99,  100,   99,   98,
       98,   98,   98,  101,   98,  102,   98,  103,  104,   98,
      105,  106,  107,  107,  107,   98,   98,   98,   98,  108,
       98,  109,  109,  109,  109,  109,  109,  109,  109,  109,
       98,   98,   98,   98,  109,  109,  110,  111,  109,  109,
      109,  109,  109,  112,  109,  109,  109,  109,  109,  113,
      109,  109,  109,  109,   98,   98,   98,   98,  141,  142,

      141,  175,  232,  175,  232,  143,  324,  144,  216,  237,
      216,  237,  323,  322,  145,  145,  145,  241,  241,  241,
      242,  321,  242,  145,  145,  145,  247,  295,  247,  295,
      295,  295,  295,  295,  320,  319,  145,  145,  145,  145,
      145,  145,  141,  142,  141,  318,  217,  317,  316,  143,
      315,  144,  176,  177,  314,  313,  312,  311,  145,  145,
      145,  310,  309,  308,  307,  306,  305,  145,  145,  145,
      304,  303,  302,  301,  300,  289,  299,  298,  297,  296,
      145,  145,  145,  145,  145,  145,   61,   61,   61,   67,
       67,   67,   70,   70,   70,   71,   71,   71,   84,   84,

       84,  114,  114,  114,  122,  122,  122,  128,  128,  128,
      134,  134,  134,  140,  140,  140,  150,  150,  150,  154,
      154,  154,  163,  163,  189,  189,  189,  197,  197,  197,
      211,  211,  211,  218,  218,  224,  224,  224,  228,  228,
      228,  233,  233,  233,  238,  238,  238,  243,  243,  243,
      248,  248,  248,  294,  293,  292,  291,  290,  289,  288,
      287,  286,  285,  284,  283,  282,  281,  280,  279,  278,
      277,  276,  275,  249,  244,  239,  234,  231,  229,  225,
      274,  273,  272,  271,  270,  212,  269,  268,  267,  266,
      265,  264,  263,  262,  261,  260,  198,  259,  258,  257,

      190,  256,  255,  254,  253,  252,  251,  155,  250,  249,
      245,  244,  240,  239,  235,  234,  231,  230,  229,  226,
      225,  222,  221,  220,  219,  213,  212,  209,  206,  205,
      202,  199,  198,  195,  192,  191,  190,  182,  181,  178,
      171,  162,  160,  155,  347,   27,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,

      347,  347,  347,  347,  347,  347,  347,  347,  347
    } ;

static yyconst short int yy_chk[710] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    3,    2,  370,    4,    5,    5,
        5,  343,    3,    5,    3,    4,   29,    4,   29,  341,
        6,    6,    6,   35,  340,    6,   15,   15,   15,  339,
       15,   60,   60,   15,  338,   15,   16,   16,   16,   15,

       16,   15,  337,   16,    5,   16,   40,   40,   40,   16,
      336,   16,   40,   55,    2,    2,    6,    9,    9,    9,
       72,    9,   72,   85,    9,   85,    9,   17,   17,   17,
       96,   35,    9,   58,   17,   58,   17,   18,   18,   18,
        9,   53,   96,   17,   18,   53,   18,    9,    9,   19,
       19,   19,  335,   18,   82,   82,   19,   93,   19,   42,
       42,   42,   55,   55,  334,   19,   19,  333,    9,    9,
        9,   10,   10,   10,   93,   10,  332,   99,   10,   99,
       10,   20,   20,   20,   58,   58,   10,   91,   20,  331,
       20,   91,  329,  108,   10,  108,  328,   20,   20,  133,

      133,   10,   10,   21,   21,   21,   25,   25,   25,   25,
       21,  115,   21,  115,   25,  123,   25,  123,  327,   21,
       21,   21,   10,   10,   10,   11,   11,   11,   22,   22,
       22,  108,   11,  325,   11,   22,  129,   22,  129,  324,
       11,  105,  105,  105,   22,   22,   22,  323,   11,   26,
       26,   26,   26,  322,   50,   50,   50,   26,  321,   26,
      107,  107,  107,   11,   50,  135,   11,  135,   11,  236,
      236,   50,  139,  139,  139,   11,  320,   11,   11,   11,
       12,   12,   12,   69,   69,   69,  141,   12,  141,   12,
      147,  319,  147,   69,  149,   12,  149,  153,  318,  153,

       69,  316,  315,   12,  158,  158,  158,  161,  161,  161,
      188,  196,  188,  196,  210,  223,  210,  223,   12,  314,
      227,   12,  227,   12,  214,  214,  214,  215,  215,  215,
       12,  313,   12,   12,   12,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   23,   23,

       23,  175,  232,  175,  232,   23,  312,   23,  216,  237,
      216,  237,  311,  310,   23,   23,   23,  241,  241,  241,
      242,  309,  242,   23,   23,   23,  247,  277,  247,  277,
      294,  295,  294,  295,  308,  307,   23,   23,   23,   23,
       23,   23,   24,   24,   24,  306,  216,  305,  304,   24,
      303,   24,  175,  175,  302,  301,  300,  299,   24,   24,
       24,  298,  297,  296,  293,  292,  290,   24,   24,   24,
      288,  287,  286,  285,  284,  283,  282,  281,  280,  278,
       24,   24,   24,   24,   24,   24,  348,  348,  348,  349,
      349,  349,  350,  350,  350,  351,  351,  351,  352,  352,

      352,  353,  353,  353,  354,  354,  354,  355,  355,  355,
      356,  356,  356,  357,  357,  357,  358,  358,  358,  359,
      359,  359,  360,  360,  361,  361,  361,  362,  362,  362,
      363,  363,  363,  364,  364,  365,  365,  365,  366,  366,
      366,  367,  367,  367,  368,  368,  368,  369,  369,  369,
      371,  371,  371,  276,  273,  272,  271,  270,  269,  268,
      267,  266,  265,  264,  263,  262,  261,  258,  257,  256,
      255,  253,  251,  248,  243,  238,  233,  231,  228,  224,
      222,  221,  220,  219,  217,  211,  209,  208,  207,  206,
      205,  204,  203,  202,  201,  200,  197,  195,  193,  192,

      189,  179,  178,  177,  176,  170,  169,  154,  152,  151,
      144,  143,  138,  137,  132,  131,  127,  126,  125,  119,
      118,  113,  112,  111,  110,  102,  101,   97,   95,   94,
       92,   88,   87,   83,   81,   76,   75,   64,   63,   59,
       54,   45,   41,   33,   27,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,

      347,  347,  347,  347,  347,  347,  347,  347,  347
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "../ParseLex/term.l"
#define INITIAL 0
#line 2 "../ParseLex/term.l"
/* term_yylex */

#include <stdio.h> 
#include <string.h>
#include "ioChar.h"
#include "types.h"
#include "lib.h"
#include "parse.h"
#include "y.tab.h"
#include "commands.h"
#include "symtab.h"       /* [H-O] ADDED THIS INCLUDE (SEE BELOW) */

#define init_position() position = 0;
#define yywrap() feof(yyin)

#define MAX_INCLUDE_DEPTH 100
     
typedef enum {
  _A, _E, _S, _INITIAL, _COMM, _SETCOMM, _QUERYCOMM, _INCLUDESTATE,
  _BINCHAR, _OCTCHAR, _DECCHAR, _HEXCHAR, _IDCHAR
} LEX_STATE;

LEX_STATE callers[_IDCHAR+1];    /* must have a element for each member *
                                  * of LEX_STATE  */

extern BBOOL FileChange(char *fileName, char *file);
extern void FileRestore(void);

extern void switchStates(LEX_STATE fromState, LEX_STATE toState);
extern char *stripquote(char *str);
extern void  yyerror(const char *msg);
extern void  inc_comLevel(void);
extern void  dec_comLevel(void);
extern int   doPrompt(void);
extern int   doEOF(void);
extern void  yyemptyInputLine(void);
extern void  yyrestoreInputLine(void);
extern FILE *FileOpen(char *fileName, char *file);

extern int lineNo;

BBOOL    readingFile  = BFALSE;
BBOOL    parsing      = BFALSE;
BBOOL    oldParsing;
BBOOL    errFlag      = BFALSE;
BBOOL    tokEOF       = BFALSE;
int comLevel = 0;
int position = 0;
int yyCurrentBufferInput[10];
int  yyCurrentBufferInputPtr = 0;

#define A 1
#define S 2
#define E 3
#define COMM 4
#define SETCOMM 5
#define QUERYCOMM 6
#define INCLUDESTATE 7
#define BINCHAR 8
#define OCTCHAR 9
#define DECCHAR 10
#define HEXCHAR 11
#define IDCHAR 12

#line 705 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 90 "../ParseLex/term.l"


#line 862 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 348 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 646 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 92 "../ParseLex/term.l"
{if (!doPrompt()) return 0;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 93 "../ParseLex/term.l"
{if (!doPrompt()) return 0;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 95 "../ParseLex/term.l"
{ parsing = BTRUE; return AMPER; }     /* [H-O] ADDED (SEE term.y) */
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 97 "../ParseLex/term.l"
{ parsing = BTRUE; return LPAR; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 98 "../ParseLex/term.l"
{ parsing = BTRUE; return RPAR; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 99 "../ParseLex/term.l"
{ parsing = BTRUE; return LUNFOLD; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 100 "../ParseLex/term.l"
{ parsing = BTRUE; return RUNFOLD; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 101 "../ParseLex/term.l"
{ parsing = BTRUE; return COMMA; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 102 "../ParseLex/term.l"
{ parsing = BTRUE; return LBRA; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 103 "../ParseLex/term.l"
{ parsing = BTRUE; return RBRA; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 104 "../ParseLex/term.l"
{ if (parsing) 
                               return COLON;
                           else {
                               parsing = BTRUE;
                               switchStates(_INITIAL, _COMM);
                               return COMMAND;
                           }    }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 111 "../ParseLex/term.l"
{ parsing = BTRUE; return NOT; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 112 "../ParseLex/term.l"
{ parsing = BTRUE; return EQUALS; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 113 "../ParseLex/term.l"
{ parsing = BTRUE; return LBRACE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 114 "../ParseLex/term.l"
{ parsing = BTRUE; return RBRACE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 115 "../ParseLex/term.l"
{ parsing = BTRUE;  return LFOLD; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 116 "../ParseLex/term.l"
{ parsing = BTRUE; return RFOLD; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 117 "../ParseLex/term.l"
{ parsing = BTRUE; return OROR; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 118 "../ParseLex/term.l"
{ parsing = BTRUE; return OR; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 119 "../ParseLex/term.l"
{ parsing = BTRUE; return IMP; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 120 "../ParseLex/term.l"
{ parsing = BTRUE; return MAPP; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 121 "../ParseLex/term.l"
{ parsing = BTRUE; yylval.string=libStrdup(parseHeapDesc,yytext);
                                 return PROD; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 123 "../ParseLex/term.l"
{ parsing = BTRUE; yylval.string=libStrdup(parseHeapDesc,yytext);
                                 return SUM; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 125 "../ParseLex/term.l"
{ parsing = BTRUE; return UNDERSCORE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 126 "../ParseLex/term.l"
{ parsing = BTRUE; return SEMI; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 127 "../ParseLex/term.l"
{ parsing = BTRUE; return RANGE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 128 "../ParseLex/term.l"
{ parsing = BFALSE;return 0; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 129 "../ParseLex/term.l"
{ tokEOF = BTRUE;  return QUIT; }
	YY_BREAK
/* [FIX] "data" AND "def" ARE TREATED EXCLUSIVELY AS KEYWORDS: */
case 28:
YY_RULE_SETUP
#line 133 "../ParseLex/term.l"
{ parsing = BTRUE; return DATA; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 134 "../ParseLex/term.l"
{ parsing = BTRUE; return DEF;  }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 136 "../ParseLex/term.l"
{ parsing = BTRUE; return READFILE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 137 "../ParseLex/term.l"
{                  return QUIT; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 138 "../ParseLex/term.l"
{ parsing = BTRUE; 
                              switchStates(_INITIAL, _QUERYCOMM); 
                              return QUERY; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 142 "../ParseLex/term.l"
{ parsing = BTRUE; yylval.string = libStrdup (parseHeapDesc, HASH_NAME); return FO_ID; }     /* [#@] */
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 143 "../ParseLex/term.l"
{ parsing = BTRUE; yylval.string = libStrdup (parseHeapDesc, AT_NAME);   return FO_ID; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 145 "../ParseLex/term.l"
{ /*
                      * [H-O] ALTERED THE LEXICAL ANALYSIS OF IDENTIFIERS. THEY ARE NOW PARTITIONED
                      *       INTO DIFFERING LEXICAL CLASSES, IE.
                      *
                      *            HO_ID: A H-O DESTRUCTOR NAME
                      *            FO_ID: ANYTHING ELSE
                      *
                      */

                     parsing       = BTRUE;
                     yylval.string = libStrdup (parseHeapDesc, yytext);

                     {
                       ST_KEY key = st_NameToKey (yytext);

                       if (key)
                         if (st_IsHO (key))
                           return HO_ID;
                         else
                           return FO_ID;
                       else
                         return FO_ID;
                     }
                   }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 170 "../ParseLex/term.l"
{ }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 171 "../ParseLex/term.l"
{ parsing = BTRUE; 
                     yylval.string = libStrdup(parseHeapDesc, yytext);
                       return INTNEG; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 174 "../ParseLex/term.l"
{ parsing = BTRUE; 
                     yylval.string = libStrdup(parseHeapDesc, yytext);
                       return INTPOS; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 177 "../ParseLex/term.l"
{ parsing = BTRUE; switchStates(_INITIAL, _BINCHAR); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 178 "../ParseLex/term.l"
{ parsing = BTRUE; switchStates(_INITIAL, _OCTCHAR); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 179 "../ParseLex/term.l"
{ parsing = BTRUE; switchStates(_INITIAL, _DECCHAR); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 180 "../ParseLex/term.l"
{ parsing = BTRUE; switchStates(_INITIAL, _HEXCHAR); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 181 "../ParseLex/term.l"
{ parsing = BTRUE; switchStates(_INITIAL, _IDCHAR); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 182 "../ParseLex/term.l"
{ oldParsing = parsing; parsing = BTRUE; 
                    switchStates(_INITIAL, _A); comLevel = 1; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 184 "../ParseLex/term.l"
{ parsing = BTRUE; comLevel = 0; switchStates(_INITIAL, _S); 
                   return QUOTE;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 187 "../ParseLex/term.l"
{ parsing = BTRUE; return ILLEGALCHAR;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 189 "../ParseLex/term.l"
{if (!doPrompt()) return 0;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 190 "../ParseLex/term.l"
{if (!doPrompt()) return 0;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 191 "../ParseLex/term.l"
{ switchStates(_BINCHAR, _A); comLevel = 1; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 192 "../ParseLex/term.l"
{ }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 193 "../ParseLex/term.l"
{ yylval.string = libStrdup(parseHeapDesc, yytext); 
                           switchStates(_BINCHAR, callers[_BINCHAR]); 
                           return BINCHARREP; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 196 "../ParseLex/term.l"
{ switchStates(_BINCHAR, callers[_BINCHAR]); 
                           return ILLEGALCHAR; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 199 "../ParseLex/term.l"
{if (!doPrompt()) return 0;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 200 "../ParseLex/term.l"
{if (!doPrompt()) return 0;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 201 "../ParseLex/term.l"
{ switchStates(_OCTCHAR, _A); comLevel = 1; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 202 "../ParseLex/term.l"
{ }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 203 "../ParseLex/term.l"
{ yylval.string = libStrdup(parseHeapDesc, yytext); 
                           switchStates(_OCTCHAR, callers[_OCTCHAR]); 
                           return OCTCHARREP; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 206 "../ParseLex/term.l"
{ switchStates(_OCTCHAR, callers[_OCTCHAR]); 
                           return ILLEGALCHAR; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 209 "../ParseLex/term.l"
{if (!doPrompt()) return 0;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 210 "../ParseLex/term.l"
{if (!doPrompt()) return 0;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 211 "../ParseLex/term.l"
{ switchStates(_DECCHAR, _A); comLevel = 1; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 212 "../ParseLex/term.l"
{ }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 213 "../ParseLex/term.l"
{ yylval.string = libStrdup(parseHeapDesc, yytext); 
                           switchStates(_DECCHAR, callers[_DECCHAR]); 
                           return DECCHARREP; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 216 "../ParseLex/term.l"
{ switchStates(_DECCHAR, callers[_DECCHAR]); 
                           return ILLEGALCHAR; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 219 "../ParseLex/term.l"
{if (!doPrompt()) return 0;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 220 "../ParseLex/term.l"
{if (!doPrompt()) return 0;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 221 "../ParseLex/term.l"
{ switchStates(_HEXCHAR, _A); comLevel = 1; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 222 "../ParseLex/term.l"
{ }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 223 "../ParseLex/term.l"
{ yylval.string = libStrdup(parseHeapDesc, yytext); 
                           switchStates(_HEXCHAR, callers[_HEXCHAR]); 
                           return HEXCHARREP; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 226 "../ParseLex/term.l"
{ switchStates(_HEXCHAR, callers[_HEXCHAR]); 
                           return ILLEGALCHAR; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 229 "../ParseLex/term.l"
{if (!doPrompt()) return 0;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 230 "../ParseLex/term.l"
{if (!doPrompt()) return 0;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 231 "../ParseLex/term.l"
{ switchStates(_IDCHAR, _A); comLevel = 1; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 232 "../ParseLex/term.l"
{ }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 233 "../ParseLex/term.l"
{ yylval.string = libStrdup(parseHeapDesc, yytext); 
                          switchStates(_IDCHAR, callers[_IDCHAR]); 
                           return IDCHARREP; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 236 "../ParseLex/term.l"
{ switchStates(_IDCHAR, callers[_IDCHAR]); 
                           return ILLEGALCHAR; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 239 "../ParseLex/term.l"
{if (!doPrompt()) return 0;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 240 "../ParseLex/term.l"
{if (!doPrompt()) return 0;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 241 "../ParseLex/term.l"
{ switchStates(_COMM, _A); comLevel = 1; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 242 "../ParseLex/term.l"
{ switchStates(_COMM, _SETCOMM); return SETCOMMAND;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 243 "../ParseLex/term.l"
{ return QUIT; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 244 "../ParseLex/term.l"
{ return READFILE; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 245 "../ParseLex/term.l"
{ return QUERY; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 246 "../ParseLex/term.l"
{  }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 247 "../ParseLex/term.l"
{ parsing = BFALSE; switchStates(_COMM, _INITIAL); return 0; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 248 "../ParseLex/term.l"
{ comLevel = 0; switchStates(_COMM, _S); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 249 "../ParseLex/term.l"
{ parsing = BTRUE; switchStates(_COMM, _INITIAL); 
                   return ILLEGALCHAR;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 252 "../ParseLex/term.l"
{if (!doPrompt()) return 0;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 253 "../ParseLex/term.l"
{if (!doPrompt()) return 0;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 254 "../ParseLex/term.l"
{ switchStates(_SETCOMM, _A); comLevel = 1; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 255 "../ParseLex/term.l"
{ return REPLACE; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 256 "../ParseLex/term.l"
{ return PRINTCTEXPR; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 257 "../ParseLex/term.l"
{ yylval.string = libStrdup(parseHeapDesc, yytext); 
                         return SYMTABENTRY;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 259 "../ParseLex/term.l"
{ yylval.string = libStrdup(parseHeapDesc, yytext); 
                       return BOOL; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 261 "../ParseLex/term.l"
{ return QUERY; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 262 "../ParseLex/term.l"
{ switchStates(_SETCOMM, _INCLUDESTATE); 
                         return INCLUDEDIRS; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 264 "../ParseLex/term.l"
{ switchStates(_SETCOMM, _INCLUDESTATE); 
                        return APPENDDIRS; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 266 "../ParseLex/term.l"
{ }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 267 "../ParseLex/term.l"
{ parsing = BFALSE; switchStates(_SETCOMM, _INITIAL); 
                      return 0; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 269 "../ParseLex/term.l"
{ parsing = BTRUE; switchStates(_SETCOMM, _INITIAL); 
                      return ILLEGALCHAR;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 272 "../ParseLex/term.l"
{if (!doPrompt()) return 0;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 273 "../ParseLex/term.l"
{if (!doPrompt()) return 0;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 274 "../ParseLex/term.l"
{ switchStates(_QUERYCOMM, _A); comLevel = 1; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 275 "../ParseLex/term.l"
{ return ABOUT; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 276 "../ParseLex/term.l"
{ return QUERY; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 277 "../ParseLex/term.l"
{return SHOWCOMB;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 278 "../ParseLex/term.l"
{ return DUMPTABLE; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 279 "../ParseLex/term.l"
{ return SHOWMEM; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 280 "../ParseLex/term.l"
{ switchStates(_QUERYCOMM, _SETCOMM); 
                             return SETCOMMAND; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 282 "../ParseLex/term.l"
{ yylval.string=libStrdup(parseHeapDesc,yytext); return PROD; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 283 "../ParseLex/term.l"
{ yylval.string=libStrdup(parseHeapDesc,yytext); return SUM; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 284 "../ParseLex/term.l"
{ yylval.string = libStrdup(parseHeapDesc, yytext);
                             return INTPOS; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 286 "../ParseLex/term.l"
{ yylval.string = libStrdup(parseHeapDesc, yytext);
                             return INTNEG; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 288 "../ParseLex/term.l"
{ yylval.string = libStrdup (parseHeapDesc, yytext);
                             return FO_ID; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 290 "../ParseLex/term.l"
{ }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 291 "../ParseLex/term.l"
{ parsing = BFALSE; 
                             switchStates(_QUERYCOMM, _INITIAL); 
                             return 0; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 294 "../ParseLex/term.l"
{ switchStates(_QUERYCOMM, _INITIAL); 
                             return ILLEGALCHAR;}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 297 "../ParseLex/term.l"
{if (!doPrompt()) return 0;}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 298 "../ParseLex/term.l"
{if (!doPrompt()) return 0;}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 299 "../ParseLex/term.l"
{ switchStates(_INCLUDESTATE, _A); comLevel = 1; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 300 "../ParseLex/term.l"
{ switchStates(_INCLUDESTATE, _S);}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 301 "../ParseLex/term.l"
{ return COMMA; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 302 "../ParseLex/term.l"
{ }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 303 "../ParseLex/term.l"
{ parsing = BFALSE; 
                           switchStates(_INCLUDESTATE, _INITIAL); return 0; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 305 "../ParseLex/term.l"
{ switchStates(_INCLUDESTATE, _INITIAL); 
                           return ILLEGALCHAR;}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 308 "../ParseLex/term.l"
{comLevel++;} 
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 309 "../ParseLex/term.l"
{if (!doPrompt()) return 0;}
	YY_BREAK
case YY_STATE_EOF(A):
#line 310 "../ParseLex/term.l"
{ if (comLevel != 0) 
                     printMsg(WARN_MSG, "Unclosed Comment"); 
                   tokEOF = BTRUE; switchStates(_A, callers[_A]); return QUIT;
                 }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 314 "../ParseLex/term.l"
{--comLevel; 
                  if (comLevel == 0) { 
                      parsing = oldParsing; 
                      switchStates(_A, callers[_A]); 
                  }   /*  fi  */ }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 319 "../ParseLex/term.l"
{ }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 321 "../ParseLex/term.l"
{switchStates(_S, _INITIAL);   return QUOTE; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 322 "../ParseLex/term.l"
{if (!doPrompt()) return 0;}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 324 "../ParseLex/term.l"
{ switchStates(_S, _BINCHAR); }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 325 "../ParseLex/term.l"
{ switchStates(_S, _OCTCHAR); }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 326 "../ParseLex/term.l"
{ switchStates(_S, _DECCHAR); }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 327 "../ParseLex/term.l"
{ switchStates(_S, _HEXCHAR); }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 328 "../ParseLex/term.l"
{ switchStates(_S, _IDCHAR); }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 329 "../ParseLex/term.l"
{ yylval.string = libStrdup(parseHeapDesc, yytext);
                     return CHAR; }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 331 "../ParseLex/term.l"
{switchStates(_S, _INITIAL);   return ILLEGALCHAR; }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 333 "../ParseLex/term.l"
ECHO;
	YY_BREAK
#line 1728 "lex.yy.c"
case YY_STATE_EOF(S):
case YY_STATE_EOF(E):
case YY_STATE_EOF(COMM):
case YY_STATE_EOF(SETCOMM):
case YY_STATE_EOF(QUERYCOMM):
case YY_STATE_EOF(INCLUDESTATE):
case YY_STATE_EOF(BINCHAR):
case YY_STATE_EOF(OCTCHAR):
case YY_STATE_EOF(DECCHAR):
case YY_STATE_EOF(HEXCHAR):
case YY_STATE_EOF(IDCHAR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 348 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 348 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 347);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 333 "../ParseLex/term.l"


typedef struct {
  YY_BUFFER_STATE yyBufferState;
  int             lineNo;
} LEX_BUFFER_STATE;

LEX_BUFFER_STATE include_stack[MAX_INCLUDE_DEPTH];
int              include_stack_ptr = 0;


/*********************************
 *                               *
 *    switchStates               *
 *                               *
 *********************************/
void
switchStates(LEX_STATE fromState, LEX_STATE toState) {

  callers[toState] = fromState;
  switch (toState) {
    case _A:            BEGIN A;            break;
    case _E:            BEGIN E;            break;
    case _S:            BEGIN S;            break;
    case _INITIAL:      BEGIN INITIAL;      break;
    case _COMM   :      BEGIN COMM;         break;
    case _SETCOMM:      BEGIN SETCOMM;      break;
    case _QUERYCOMM:    BEGIN QUERYCOMM;    break;
    case _INCLUDESTATE: BEGIN INCLUDESTATE; break;
    case _BINCHAR:      BEGIN BINCHAR;      break;
    case _OCTCHAR:      BEGIN OCTCHAR;      break;
    case _DECCHAR:      BEGIN DECCHAR;      break;
    case _HEXCHAR:      BEGIN HEXCHAR;      break;
    case _IDCHAR:       BEGIN IDCHAR;       break;
    default:
      printMsg(FATAL_MSG,"term.l - %d is not a valid LEX_STATE value",toState);
   }

}


/*********************************
 *                               *
 *    stripquote                 *
 *                               *
 *********************************/
char
*stripquote(char *str)
{
     char *result = str;
     int   count  = 0;

     while (str[count] != '\0') {
        if (str[count] == '"') {
           str[count] = '\0';
           break;
        }
        count++;
     }
     return(result);
}


/*********************************
 *                               *
 *    yyerror                    *
 *                               *
 *********************************/
void
yyerror(const char *msg)
{
  /* There should be no limit on the amount of syntax errors tolerated.
     Semantic errors, on the other hand, are a different story */
  int token;

  errFlag = BTRUE;

  if (tokEOF && readingFile) {
    printMsg(DELAYEDERROR_MSG, "Syntax: Unexpected EOF");
    ParseResult.tag = QUIT;
  }
  else {
    printMsg(DELAYEDERROR_MSG, "Syntax: line %d at or before token `%s'.",lineNo,yytext);  

    if (parsing) {
      token = yylex();
      while (token && !tokEOF) 
        token = yylex();
    }
    ParseResult.tag = EMPTY_INPUT; 
  }
  parsing = BFALSE;
  errFlag = BFALSE;
}


/*********************************
 *                               *
 *    FileChange                 *
 *                               *
 *********************************/
BBOOL
FileChange(char *fileName, char *file)
{
     FILE *oldfile = yyin;
     int   oldLineNo = lineNo;

     if ( include_stack_ptr >= MAX_INCLUDE_DEPTH ) 
	  printMsg(FATAL_MSG, "FileChange(): Max number of nested files (%d) exceeded.", MAX_INCLUDE_DEPTH );
     
     include_stack[include_stack_ptr].yyBufferState = YY_CURRENT_BUFFER;
     include_stack[include_stack_ptr].lineNo = lineNo;
     include_stack_ptr++;

     yyin = FileOpen(fileName, file);

     if ( ! yyin ) {
	  include_stack_ptr--;
	  yyin = oldfile;
          lineNo = oldLineNo;
          return(BFALSE);
     }
     else {
	  yy_switch_to_buffer( yy_create_buffer( yyin, YY_BUF_SIZE ) );
          lineNo = 1;
     }
     return(BTRUE);
}


/*********************************
 *                               *
 *    FileOpen                   *
 *                               *
 *********************************/
FILE *
FileOpen(char *fileName, char *file) 
{
  char     *dir;
  STR_LIST *includeDirs = g_strList_IncludeDirs;
  FILE     *openedFile  = NULL;

  while (includeDirs && !openedFile) {
    dir = StrListHead(includeDirs);
    includeDirs = StrListTail(includeDirs);
    strcpy(fileName, dir);
    strcat(fileName, DIR_SEPARATOR);
    strcat(fileName, file);
    openedFile = fopen(fileName, "r");
  }
    
  return(openedFile);

}


/*********************************
 *                               *
 *    FileRestore                *
 *                               *
 *********************************/
void
FileRestore(void) 
{
     if ( --include_stack_ptr < 0 ) 
	  printMsg(FATAL_MSG, "FileRestore():  No nested files to restore.");
     else {
	  yy_delete_buffer( YY_CURRENT_BUFFER );
	  yy_switch_to_buffer(include_stack[include_stack_ptr].yyBufferState );
          lineNo = include_stack[include_stack_ptr].lineNo;
     }
     if (include_stack_ptr == 0)
       readingFile = BFALSE;
     tokEOF = BFALSE;
}


/*********************************
 *                               *
 *    doPrompt                   *
 *                               *
 *********************************/
int
doPrompt(void)
{
  if (readingFile)
    lineNo++;
  else if (parsing && !errFlag) {
      lineNo++;
      printMsg(PROMPT_MSG, CHARITY_CONT_PROMPT);
    }
  else {
    lineNo = 1;
    printMsg(PROMPT_MSG, CHARITY_PROMPT);
  }

  if (!readingFile && errFlag) 
    return 0;
  else
    return 1;

}   /*  end doPrompt()  */


/*********************************
 *                               *
 *    yyemptyInputLine           *
 *                               *
 *********************************/
void 
yyemptyInputLine(void) {

  int      i=0;
  int c;

  if (include_stack_ptr != 0) {
    while (i<include_stack_ptr && 
           !include_stack[i].yyBufferState->yy_is_interactive)
        i++;
    if (i == include_stack_ptr)
      printMsg(FATAL_MSG,"emptyInputLine(): Couldn't find interactive buffer");

    include_stack[include_stack_ptr].yyBufferState = YY_CURRENT_BUFFER;
    include_stack[include_stack_ptr].lineNo = lineNo;
    yy_switch_to_buffer(include_stack[i].yyBufferState);
  } 

  do {
    c = input();
    yyCurrentBufferInput[yyCurrentBufferInputPtr++] = c;
  } while (c != '\n');

}


/*********************************
 *                               *
 *    yyrestoreInputLine         *
 *                               *
 *********************************/
void 
yyrestoreInputLine(void) {

  while (yyCurrentBufferInputPtr)
    unput(yyCurrentBufferInput[--yyCurrentBufferInputPtr]);

  if (include_stack_ptr != 0) {
    yy_switch_to_buffer(include_stack[include_stack_ptr].yyBufferState);
    lineNo = include_stack[include_stack_ptr].lineNo;
  }

}

